#!/bin/bash

# Use date + file number
# exiftool '-FileName<${CreateDate}_$filenumber.jpg' -d %Y-%m-%d -ext jpg .

# Use date + original filename
exiftool '-FileName<${CreateDate}_$filename.jpg' -d %Y-%m-%d -ext jpg .
